### PR TITLE
feat(ws): add `containerSecurityContext` to WorkspaceKind

### PR DESCRIPTION
**Pull request by thesuperzapper**
This PR brings the CRD spec into line with the latest updates from https://github.com/thesuperzapper/kubeflow-notebooks-v2-design/commit/7aeb44d4c7abf7977eed2ec2ce2d3309b935ba97.

The most important changes are:

- Added a `spec.podTemplate.containerSecurityContext` to the `WorkspaceKind`
- Made all optional CRD fields into pointers
    - For example, we made `WorkspacePodMetadata` into `*WorkspacePodMetadata`
    - ___NOTE:__ this is required to distinguish between unset and empty values, and is [recommended by Kubernetes](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#optional-vs-required)._
- Updated the descriptions of CRD fields to keep them in line with the sample

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@jiridanek @ederign @Adembc, for your reference.

**Comment by thesuperzapper** [comment]
@ederign while we wait for @jiridanek to be a member (so he can LGM), can you LGTM this so we can make future PRs based on it?

Since `notebooks-v2` is not released its not a big deal if it's only a basic review.

**Review by jiridanek — APPROVED** [review]
/lgtm

**Comment by thesuperzapper** [comment]
@jiridanek thanks

/approve

**Pull request merged**
