### PR TITLE
feat(ws): update `Workspace` and `WorkspaceKind` definitions 

### PR DESCRIPTION
**Pull request by thesuperzapper**
This PR continues from https://github.com/kubeflow/notebooks/pull/6.

It makes the following changes to align with the updates discussed, see https://github.com/thesuperzapper/kubeflow-notebooks-v2-design/commit/ee651ee56045956efa5cde33b034e4ef026b2cf3 for the changes.

The key changes are:

- Renaming some of the Go types because they were likely to overlap with future ones, e.g. `PodVolumes` became `WorkspacePodVolumes`.
- Add spec for labels on each spawner option, to be used as filters the UI when selecting from options.
- Add status for WorkspaceKind which lists the options and how many Workspaces are using them
- Add redirect "message" to be displayed in the UI when warning users about the update.

I have also re-ordered the types and added section headings to make the go files easier to read.

### CODE REVIEW

**Comment by thesuperzapper** [comment]
I cant assign @jiridanek as a reviewer because he is not a member yet, but please take a look.

**Comment by jiridanek** [comment]
look taken

/lgtm

**Review by ederign — APPROVED** [review]

**Pull request merged**
