### PR TITLE
feat: automates backend deployment

### PR DESCRIPTION
**Pull request by KapilSareen**
## Description:

This PR automates the deployment process for the application's backend component, resolving the issue mentioned in #45. It introduces two new Makefile commands, `deploy` and `undeploy`, which streamline the process of deploying and undeploying the application on a Kubernetes cluster.

Additionally, some fixes have been applied to the `Dockerfile` and `go.mod` to address issues preventing the successful execution of the `docker-build` command.

### CODE REVIEW

**Comment by KapilSareen** [comment]
Hi @kimwnasptd, any updates on this?

**Review by ederign — CHANGES_REQUESTED** [review]
This PR will require some work. On controller, we use kustomize and we need to follow the same procedure that we are using on [controller](https://github.com/kubeflow/notebooks/blob/notebooks-v2/workspaces/controller/Makefile).

Besides that, we are going to also discuss further points i.e. roles, services and service accounts. I've added it as a topic to define this topology on our next community call. 2024-11-21 8:00 AM PT (check kubeflow calendar for the link).

@KapilSareen my recommendation right now, until we have such definitions, is if you find any issues with our docker image build, maybe repurpose this PR to fix them? 

Then we can address the automate deployment after the definitions on the community call.

**Comment by KapilSareen** [comment]
That sounds great! I've repurposed the PR to address that. However, I have other commitments around the time of the community call. Please do share the insights, and I'll make sure to work on them.

**Comment by KapilSareen** [comment]
Hey @ederign can you brief what was decided about this in the recent community call?

**Comment by thesuperzapper** [comment]
I dont think this PR is addressing any current issues and would actually break the relative import of the controller code, I am going to close it.

/close

**Pull request closed without merging**
