### PR TITLE
chore(ws): restructure frontend and setup navigation

### PR DESCRIPTION
**Pull request by Griffin-Sullivan**
Restructuring the frontend to have the right directory layout. I also updated some things like README, package.json, tsconfig, webpack config, and added routes / navigation.

Most of this reflects how model registry is set up.

### CODE REVIEW

**Review by ederign — CHANGES_REQUESTED** [review]
@Griffin-Sullivan overall looks good.

Do you mind to run npm audit fix in your PR? I got here and automatically fixed all vulnerabilities.

https://gist.github.com/ederign/6736f23cf5814328e92e07a8a95711b8

**Review by ederign — APPROVED** [review]

**Comment by thesuperzapper** [comment]
@Griffin-Sullivan @ederign I think something about what you changed requires the front end test GitHub workflow to be updated:
- https://github.com/kubeflow/notebooks/blob/notebooks-v2/.github/workflows/ui-frontend-build.yml

It's probably best if we try and get it to pass before merging, unless you have already started another PR based on this one.

**Comment by Griffin-Sullivan** [comment]
Do I need to become a member of Kubeflow for the workflow to run without approval?

**Comment by thesuperzapper** [comment]
> Do I need to become a member of Kubeflow for the workflow to run without approval?

@Griffin-Sullivan, no once you get your first PR merged on the repo it will be fine.

**Comment by Griffin-Sullivan** [comment]
apparently no tests == fail..... I'll add back the Jest test I removed and then re-remove when I add Cypress in the next PR.

**Comment by thesuperzapper** [comment]
@Griffin-Sullivan it looks like the CI is still failing, cant you just add a nothing test, and ensure that all the other steps in the GitHub workflow succeed?

That will make it easier when we add new tests.

**Comment by Griffin-Sullivan** [comment]
I could but I see that as pointless work when I could just fix the github action. Looks like I accidentally removed an npm command that should've stayed.

**Comment by Griffin-Sullivan** [comment]
Ok fairly confident in this one :laughing:

**Comment by thesuperzapper** [comment]
@Griffin-Sullivan we can merge this for now, but please remember to re-add the test call in the github action in your next PR, otherwise we will probably forget.

/lgtm
/approve

**Pull request merged**
